spring:
  application.name: webui

  datasource.url: jdbc:h2:mem:webui;MODE=MySQL
  datasource.username: webui
  datasource.password: changeit13579

  h2.console.enabled: true

  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

security:
  user:
    name: webui
    password: changeit13579
    roles: ACTUATOR, ADMIN
  ignored: /inde.html, /webjars/**, /h2-console**

server:
  port: 8080
  contextPath: /webui
