spring:
  application.name: webui
  resources.static-locations: classpath:/public/,file:images/

  datasource.url: jdbc:h2:mem:webui;MODE=MySQL
  datasource.username: webui
  datasource.password: changeit13579

  h2.console.enabled: true

  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy

security:
  user:
    name: admin
    password: $2a$10$GMmB1mbxYwMd8Cm68Y/J8O8VXAmQc1LhYkNXF5yNF4arppTwPnMqm
    roles: ACTUATOR,ADMIN

server:
  port: 8080
  contextPath: /webui

management:
  context-path: /actuator
